"use client";

import { useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import PanelDataTable, { Column } from "@/components/panel/PanelDataTable";
import { Button } from "@/components/ui/button";
import { Download, FileText, Plus } from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { jsPDF } from "jspdf";
import { useCollegeReports, useCollegeAttendanceSummary } from "@/hooks/queries/useCollege";
import type { CollegeMonthlyReport } from "@/types/college";

type Report = CollegeMonthlyReport;

const downloadReportPdf = (report: Report) => {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const left = 56;
  let y = 80;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("GrowthCraft", left, y);

  doc.setFontSize(14);
  doc.setTextColor(120);
  y += 24;
  doc.text("Campus Program Report", left, y);

  doc.setDrawColor(220);
  y += 16;
  doc.line(left, y, 539, y);

  doc.setTextColor(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  y += 40;
  doc.text(report.month, left, y);

  const rows: [string, string][] = [
    ["Total Enrollments", String(report.enrollments)],
    ["Completion Rate", report.completionRate],
  ];

  doc.setFontSize(12);
  rows.forEach(([label, value]) => {
    y += 28;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(110);
    doc.text(label, left, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20);
    doc.text(value, 539, y, { align: "right" });
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160);
  doc.text("Generated by GrowthCraft", left, 800);

  doc.save(`growthcraft-report-${report.month.replace(/\s+/g, "-").toLowerCase()}.pdf`);
};

const MONTH_NAMES = [
  "jan", "feb", "mar", "apr", "may", "jun",
  "jul", "aug", "sep", "oct", "nov", "dec",
];

const parseReportMonth = (month: string) => {
  const [name, year] = month.toLowerCase().split(" ");
  return new Date(Number(year), MONTH_NAMES.indexOf(name.slice(0, 3)), 1);
};

const formatRange = (from: string, to: string) => {
  if (from && to) return `${from} to ${to}`;
  if (from) return `From ${from}`;
  if (to) return `Up to ${to}`;
  return "All time";
};

const downloadCustomReportPdf = (
  allReports: Report[],
  from: string,
  to: string,
  selectedMetrics: string[]
) => {
  const inRange = allReports.filter((r) => {
    const d = parseReportMonth(r.month);
    if (from && d < new Date(from)) return false;
    if (to && d > new Date(to)) return false;
    return true;
  });
  const periodReports = inRange.length ? inRange : allReports;

  const totalEnrollments = periodReports.reduce((sum, r) => sum + r.enrollments, 0);
  const avgCompletion = periodReports.length
    ? Math.round(
        periodReports.reduce((sum, r) => sum + parseFloat(r.completionRate), 0) /
          periodReports.length
      )
    : 0;

  const metricValue = (metric: string): string => {
    switch (metric) {
      case "Enrollments":
        return String(totalEnrollments);
      case "Completion Rate":
        return `${avgCompletion}%`;
      default:
        return "Included";
    }
  };

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const left = 56;
  let y = 80;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("GrowthCraft", left, y);

  doc.setFontSize(14);
  doc.setTextColor(120);
  y += 24;
  doc.text("Custom Campus Report", left, y);

  doc.setFontSize(11);
  y += 20;
  doc.text(`Period: ${formatRange(from, to)}`, left, y);
  y += 16;
  doc.text(`Months covered: ${periodReports.length}`, left, y);

  doc.setDrawColor(220);
  y += 16;
  doc.line(left, y, 539, y);

  doc.setFontSize(12);
  selectedMetrics.forEach((metric) => {
    y += 28;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(110);
    doc.text(metric, left, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20);
    doc.text(metricValue(metric), 539, y, { align: "right" });
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160);
  doc.text("Generated by GrowthCraft", left, 800);

  doc.save("growthcraft-custom-report.pdf");
};

const columns: Column<Report>[] = [
  {
    key: "month",
    label: "Month",
    sortable: true,
    render: (row) => (
      <div className="flex items-center gap-2">
        <FileText className="h-4 w-4 text-muted-foreground" />
        <span className="font-medium text-sm">{row.month}</span>
      </div>
    ),
  },
  { key: "enrollments", label: "Total Enrollments", sortable: true },
  { key: "completionRate", label: "Completion Rate", sortable: true },
  {
    key: "actions",
    label: "",
    render: (row) => (
      <Button variant="ghost" size="sm" onClick={() => downloadReportPdf(row)}>
        <Download className="h-4 w-4 mr-1" /> PDF
      </Button>
    ),
  },
];

const metrics = ["Enrollments", "Completion Rate", "Student Progress", "Placement Stats", "Mentor Sessions"];

interface AttendanceSummaryRow {
  studentName: string;
  batchTitle: string;
  totalSessions: number;
  present: number;
  absent: number;
  late: number;
  attendancePercent: number;
}

const attendanceColumns: Column<AttendanceSummaryRow>[] = [
  { key: "studentName", label: "Student Name", sortable: true },
  { key: "batchTitle", label: "Batch", sortable: true },
  { key: "totalSessions", label: "Total Sessions", sortable: true },
  { key: "present", label: "Present", sortable: true },
  { key: "absent", label: "Absent", sortable: true },
  { key: "late", label: "Late", sortable: true },
  {
    key: "attendancePercent",
    label: "Attendance Rate",
    sortable: true,
    render: (row) => (
      <span className={`font-semibold ${row.attendancePercent >= 75 ? "text-emerald-600" : "text-amber-600"}`}>
        {row.attendancePercent}%
      </span>
    ),
  },
];

const CollegeReports = () => {
  const [activeTab, setActiveTab] = useState<"monthly" | "attendance">("monthly");
  const { data: reportsData, isLoading: reportsLoading } = useCollegeReports();
  const { data: attendanceData, isLoading: attendanceLoading } = useCollegeAttendanceSummary();

  const reports = reportsData?.data?.reports ?? [];
  const attendanceRows = (attendanceData?.data ?? []) as AttendanceSummaryRow[];

  const [modalOpen, setModalOpen] = useState(false);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [selectedMetrics, setSelectedMetrics] = useState<string[]>(metrics);

  const toggleMetric = (metric: string, checked: boolean) => {
    setSelectedMetrics((prev) =>
      checked ? [...prev, metric] : prev.filter((m) => m !== metric)
    );
  };

  const handleGenerate = () => {
    if (selectedMetrics.length === 0) {
      toast.error("Select at least one metric", {
        description: "Choose one or more metrics to include in the report.",
      });
      return;
    }
    if (fromDate && toDate && fromDate > toDate) {
      toast.error("Invalid date range", {
        description: "The 'From' date must be on or before the 'To' date.",
      });
      return;
    }

    const ordered = metrics.filter((m) => selectedMetrics.includes(m));
    downloadCustomReportPdf(reports, fromDate, toDate, ordered);
    toast.success("Report generated", {
      description: "Your custom report has been downloaded.",
    });
    setModalOpen(false);
  };

  const handleExportCSV = () => {
    if (!attendanceRows || attendanceRows.length === 0) {
      toast.error("No attendance data to export");
      return;
    }

    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Student Name,Batch,Total Sessions,Present,Absent,Late,Attendance Rate (%)\n";

    attendanceRows.forEach((row) => {
      csvContent += `"${row.studentName}","${row.batchTitle}",${row.totalSessions},${row.present},${row.absent},${row.late},${row.attendancePercent}\n`;
    });

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `attendance_summary_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("CSV Exported successfully!");
  };

  const renderMobileMonthlyCard = (row: Report) => {
    return (
      <div className="space-y-3.5 text-xs">
        {/* Top: Month Header */}
        <div className="flex items-center gap-2 pb-2.5 border-b border-border/40 justify-between">
          <div className="flex items-center gap-2 min-w-0">
            <FileText className="h-4 w-4 text-magenta shrink-0" />
            <span className="font-semibold text-sm text-foreground truncate">{row.month}</span>
          </div>
          <span className="font-bold text-magenta bg-magenta/5 border border-magenta/10 px-2.5 py-0.5 rounded-full text-[10px] whitespace-nowrap shrink-0">Monthly Summary</span>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-0.5">
            <span className="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Total Enrollments</span>
            <p className="text-sm font-bold text-foreground">{row.enrollments}</p>
          </div>
          <div className="space-y-0.5">
            <span className="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Completion Rate</span>
            <p className="text-sm font-bold text-foreground">{row.completionRate}</p>
          </div>
        </div>

        {/* Download Action */}
        <div className="pt-2.5 border-t border-border/40 mt-1">
          <Button
            variant="outline"
            size="sm"
            onClick={() => downloadReportPdf(row)}
            className="w-full h-9 text-xs font-semibold border-border hover:bg-magenta hover:text-white transition-colors rounded-xl flex items-center justify-center gap-1.5"
          >
            <Download className="h-3.5 w-3.5" /> Download PDF Report
          </Button>
        </div>
      </div>
    );
  };

  const renderMobileAttendanceCard = (row: AttendanceSummaryRow) => {
    return (
      <div className="space-y-3.5 text-xs">
        {/* Top: Student & Batch */}
        <div className="pb-2.5 border-b border-border/40 flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h4 className="text-sm font-semibold text-foreground truncate">{row.studentName}</h4>
            <p className="text-[11px] text-muted-foreground truncate mt-0.5">{row.batchTitle}</p>
          </div>
          <span className={`shrink-0 font-bold px-2.5 py-0.5 rounded-full text-[11px] border ${
            row.attendancePercent >= 75
              ? "bg-emerald-50 text-emerald-700 border-emerald-100"
              : "bg-amber-50 text-amber-700 border-amber-100"
          }`}>
            {row.attendancePercent}%
          </span>
        </div>

        {/* Attendance summary items */}
        <div className="grid grid-cols-4 gap-2 text-center bg-slate-50/50 p-2.5 rounded-xl border border-border/40">
          <div>
            <span className="text-[9px] text-muted-foreground font-medium uppercase tracking-wider">Total</span>
            <p className="font-bold text-foreground mt-0.5">{row.totalSessions}</p>
          </div>
          <div>
            <span className="text-[9px] text-muted-foreground font-medium uppercase tracking-wider text-emerald-600">Present</span>
            <p className="font-bold text-emerald-600 mt-0.5">{row.present}</p>
          </div>
          <div>
            <span className="text-[9px] text-muted-foreground font-medium uppercase tracking-wider text-rose-500">Absent</span>
            <p className="font-bold text-rose-500 mt-0.5">{row.absent}</p>
          </div>
          <div>
            <span className="text-[9px] text-muted-foreground font-medium uppercase tracking-wider text-amber-500">Late</span>
            <p className="font-bold text-amber-500 mt-0.5">{row.late}</p>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6 sm:space-y-8 p-4 sm:p-0">
      <PageHeader
        title="Campus Insights"
        description="Monitor student progress, monthly program reports, and attendance summaries."
        className="text-center md:text-left"
        action={
          activeTab === "monthly" ? (
            <Button onClick={() => setModalOpen(true)} className="bg-magenta hover:bg-magenta/90 text-white w-full sm:w-auto h-10 rounded-xl font-semibold">
              <Plus className="h-4 w-4 mr-2 inline" /> Generate Custom Report
            </Button>
          ) : (
            <Button onClick={handleExportCSV} className="bg-magenta hover:bg-magenta/90 text-white w-full sm:w-auto h-10 rounded-xl font-semibold">
              <Download className="h-4 w-4 mr-2 inline" /> Export CSV Ledger
            </Button>
          )
        }
      />

      {/* Tabs Switcher */}
      <div className="flex border-b border-slate-200 overflow-x-auto scrollbar-hide flex-nowrap w-full">
        <button
          onClick={() => setActiveTab("monthly")}
          className={`py-3 px-6 text-sm font-semibold border-b-2 transition-all shrink-0 ${
            activeTab === "monthly"
              ? "border-magenta text-magenta"
              : "border-transparent text-slate-500 hover:text-slate-800"
          }`}
        >
          Monthly Reports
        </button>
        <button
          onClick={() => setActiveTab("attendance")}
          className={`py-3 px-6 text-sm font-semibold border-b-2 transition-all shrink-0 ${
            activeTab === "attendance"
              ? "border-magenta text-magenta"
              : "border-transparent text-slate-500 hover:text-slate-800"
          }`}
        >
          Student Attendance
        </button>
      </div>

      {activeTab === "monthly" ? (
        reportsLoading ? (
          <p className="text-xs sm:text-sm text-slate-500">Loading reports…</p>
        ) : (
          <PanelDataTable
            columns={columns}
            data={reports}
            pageSize={10}
            className="border-border/60"
            mobileRender={renderMobileMonthlyCard}
          />
        )
      ) : attendanceLoading ? (
        <p className="text-xs sm:text-sm text-slate-500">Loading attendance summaries…</p>
      ) : (
        <PanelDataTable
          columns={attendanceColumns}
          data={attendanceRows}
          pageSize={10}
          className="border-border/60"
          mobileRender={renderMobileAttendanceCard}
        />
      )}

      <Dialog open={modalOpen} onOpenChange={setModalOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Generate Custom Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>From</Label>
                <Input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label>To</Label>
                <Input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} />
              </div>
            </div>
            <div className="space-y-2">
              <Label>Metrics to include</Label>
              <div className="space-y-2">
                {metrics.map((m) => (
                  <div key={m} className="flex items-center gap-2">
                    <Checkbox
                      id={m}
                      checked={selectedMetrics.includes(m)}
                      onCheckedChange={(checked) => toggleMetric(m, checked === true)}
                    />
                    <label htmlFor={m} className="text-sm">
                      {m}
                    </label>
                  </div>
                ))}
              </div>
            </div>
            <div className="flex justify-end gap-3">
              <Button variant="outline" onClick={() => setModalOpen(false)}>
                Cancel
              </Button>
              <Button className="bg-magenta hover:bg-magenta/90 text-white" onClick={handleGenerate}>
                Generate
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default CollegeReports;
