/**
 * API Endpoints
 * Centralized definition of all API routes
 */

export const API_ENDPOINTS = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    profile: "/auth/profile",
    logout: "/auth/logout",
    logoutAll: "/auth/logout-all",
    refresh: "/auth/refresh",
    changePassword: "/auth/change-password",
  },
  users: {
    update: (id: string) => `/users/${id}`,
  },
  // Future endpoints can be added here
  courses: {
    list: "/courses",
    detail: (id: string) => `/courses/${id}`,
    detailBySlug: (slug: string) => `/courses/slug/${slug}`,
    enroll: (id: string) => `/courses/${id}/enroll`,
    requestCallback: (id: string) => `/courses/${id}/request-callback`,
    enrollmentStatus: (id: string) => `/courses/${id}/enrollment-status`,
    config: "/courses/config",
  },
  bootcamps: {
    list: "/bootcamps",
    detail: (id: string) => `/bootcamps/${id}`,
  },
  trainingPrograms: {
    list: "/training-programs",
    detail: (id: string) => `/training-programs/${id}`,
    basicBySlug: (slug: string) => `/training-programs/${slug}`,
    detailsBySlug: (slug: string) => `/training-programs/${slug}/details`,
    similarBySlug: (slug: string) => `/training-programs/${slug}/similar`,
    enroll: (id: string) => `/training-programs/${id}/enroll`,
    requestCallback: (id: string) => `/training-programs/${id}/request-callback`,
    domains: "/training-programs/filters/domains",
    enrollmentStatus: (id: string) => `/training-programs/${id}/enrollment-status`,
  },
  events: {
    list: "/events",
    detail: (id: string) => `/events/${id}`,
    detailBySlug: (slug: string) => `/events/slug/${slug}`,
    detailBySlugV2: (slug: string) => `/events/${slug}/details`,
    register: (id: string) => `/events/${id}/register`,
    requestCallback: (id: string) => `/events/${id}/request-callback`,
    registerByType: (type: string, id: string) => `/events/${type}/${id}/register`,
    requestCallbackByType: (type: string, id: string) => `/events/${type}/${id}/request-callback`,
    config: "/events/config",
  },
  workshops: {
    list: "/workshops",
  },
  hackathons: {
    list: "/hackathons",
  },
  students: {
    dashboard: "/students/dashboard",
    profile: "/students/profile",
    courses: "/students/courses",
    bootcamps: "/students/bootcamps",
    workshops: "/students/workshops",
    hackathons: "/students/hackathons",
    events: "/students/events",
    trainingPrograms: "/students/training-programs",
    certificates: "/students/certificates",
    support: "/students/support",
    mentors: "/students/mentors",
    mentorSessions: "/students/mentor-sessions",
    ambassadorActivate: "/students/ambassador/activate",
    ambassadorDashboard: "/students/ambassador/dashboard",
    ambassadorReferrals: "/students/ambassador/referrals",
    ambassadorInvite: "/students/ambassador/invite",
    ambassadorEarnings: "/students/ambassador/earnings",
    jobs: "/students/jobs",
    applyJob: (id: string) => `/students/jobs/${id}/apply`,
    applications: "/students/applications",
    uploadResume: "/students/resume/upload",
    batches: "/students/batches",
  },
  colleges: {
    dashboard: "/colleges/dashboard",
    cohort: "/colleges/cohort",
    students: "/colleges/students",
    studentsImport: "/colleges/students/import",
    profile: "/colleges/profile",
    partnership: "/colleges/partnership",
    subscription: "/colleges/subscription",
    upgradeRequest: "/colleges/partnership/upgrade-request",
    reports: "/colleges/reports",
    settings: "/colleges/settings",
    settingsAccount: "/colleges/settings/account",
    settingsNotifications: "/colleges/settings/notifications",
    support: "/colleges/support",
    ambassadors: "/colleges/ambassadors",
    deleteAmbassador: (studentId: string) => `/colleges/ambassadors/${studentId}`,
    attendance: "/colleges/attendance",
    attendanceSummary: "/colleges/attendance/summary",
    attendanceExport: "/colleges/attendance/export",
    eventStudents: (eventId: string) => `/colleges/events/${eventId}/students`,
    eventAccess: (eventId: string) => `/colleges/events/${eventId}/access`,
  },
  admin: {
    batches: "/admin/batches",
    batchDetail: (id: string) => `/admin/batches/${id}`,
    enrollments: "/admin/enrollments",
    users: "/admin/users",
    userDetail: (id: string) => `/admin/users/${id}`,
    ambassadors: "/admin/ambassadors",
    ambassadorPayout: (id: string) => `/admin/ambassadors/${id}/payout`,
    ambassadorActivate: (id: string) => `/admin/ambassadors/${id}/activate`,
    mentors: "/admin/mentors",
    availableMentors: "/admin/mentors/available",
    mentorDetail: (id: string) => `/admin/mentors/${id}`,
    mentorCheckIns: (id: string) => `/admin/mentors/${id}/check-ins`,
    verifyCheckIn: (mentorId: string, checkInId: string) => `/admin/mentors/${mentorId}/check-ins/${checkInId}/verify`,
    mentorPayouts: (id: string) => `/admin/mentors/${id}/payouts`,
    recordPayout: (id: string) => `/admin/mentors/${id}/payout`,
    globalPayouts: "/admin/mentor-payouts",
    mentorAvailability: (id: string) => `/admin/mentors/${id}/availability`,
    attendance: "/admin/attendance",
    attendanceSummary: (batchId: string) => `/admin/attendance/batch/${batchId}/summary`,
    revenue: "/admin/revenue",
    analytics: "/admin/analytics",
    auditLogs: "/admin/audit-logs",
    courses: "/admin/courses",
    coursePublish: (id: string) => `/admin/courses/${id}/publish`,
    courseDetail: (id: string) => `/admin/courses/${id}`,
    trainingPrograms: "/admin/training-programs",
    trainingProgramPublish: (id: string) => `/admin/training-programs/${id}/publish`,
    trainingProgramDetail: (id: string) => `/admin/training-programs/${id}`,
    events: "/admin/events",
    eventPublish: (id: string) => `/admin/events/${id}/publish`,
    eventDetail: (id: string) => `/admin/events/${id}`,
    colleges: "/admin/colleges",
    collegeDetail: (id: string) => `/admin/colleges/${id}`,
    employers: "/admin/employers",
    employerDetail: (id: string) => `/admin/employers/${id}`,
    upload: "/admin/upload",
  },
  leads: {
    create: "/leads",
  },
  mentor: {
    dashboard: "/mentor/dashboard",
    sessions: "/mentor/sessions",
    updateSessionStatus: (id: string) => `/mentor/sessions/${id}/status`,
    availability: "/mentor/availability",
    students: "/mentor/students",
    earnings: "/mentor/earnings",
    withdraw: "/mentor/earnings/withdraw",
    profile: "/mentor/profile",
    support: "/mentor/support",
    settingsAccount: "/mentor/settings/account",
    settingsPassword: "/mentor/settings/password",
    batches: "/mentor/batches",
    batchDetail: (id: string) => `/mentor/batches/${id}`,
    checkIn: "/mentor/check-in",
    checkOut: "/mentor/check-out",
    checkInStatus: "/mentor/check-in/status",
    checkInsHistory: "/mentor/check-ins",
    attendance: "/mentor/attendance",
    progressNotes: "/mentor/progress-notes",
  },
  employers: {
    dashboard: "/employers/dashboard",
    jobs: "/employers/jobs",
    jobStatus: (id: string) => `/employers/jobs/${id}/status`,
    jobDetail: (id: string) => `/employers/jobs/${id}`,
    profile: "/employers/profile",
    applications: "/employers/applications",
    applicationStatus: (id: string) => `/employers/applications/${id}/status`,
  },
  talent: {
    list: "/talent",
  },
  publicJobs: {
    list: "/public/jobs",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
  },
  payments: {
    createOrder: "/payments/create-order",
    verify: "/payments/verify",
    createLink: "/payments/create-link",
    myPayments: "/payments/my-payments",
  },
} as const;


